#include "app_state.h"
ThreeWire myWire(RTC_DAT, RTC_CLK, RTC_RST);
RtcDS1302<ThreeWire> Rtc(myWire);
HardwareSerial SerialDFPlayer(2);
DFRobotDFPlayerMini dfPlayer;
const char* WIFI_SSID     = "wipo";
const char* WIFI_PASSWORD = "123456789";
const char* SUPABASE_URL      = "https://zuspjabuphigtfuvzhye.supabase.co";
const char* SUPABASE_ANON_KEY = "sb_publishable_q_d3qn_GC5ml_i-aU2K6NA_oK9TEkxJ";
const char* DEVICE_ID_STR    = "SB-001";
const char* DEVICE_NAME      = "Smart Bell";
const char* FIRMWARE_VERSION = "0.11.0";
const char* DEVICE_TOKEN = "ac640bc3427b17e7f411e69f7bbafd786d5b371c7d176da95acec0de2961d01f";
bool relay1State = false, relay2State = false, rtcOk = false, wifiOk = false, pttWsInitialized = false, internetOk = false, supabaseRegistered = false;
unsigned long lastHeartbeatMs = 0, lastRtcCheckMs = 0, lastLedToggleMs = 0, lastRtcTestMs = 0, lastRtcRawTestMs = 0;
bool ledOn = false, wifiConnecting = false, wifiDisconnectPending = false;
unsigned long wifiAttemptStartMs = 0, wifiDisconnectMs = 0, wifiLastRetryMs = 0;
bool ntpSynced = false;
unsigned long lastNtpSyncMs = 0;
bool ntpInProgress = false;
unsigned long ntpStartMs = 0;
bool ntpManualSyncReq = false;
bool dfPlayerOk = false, microSdOk = false, dfPlayerPlaying = false;
uint8_t currentTrack = 0, dfVolume = 25;
BellState bellState = BELL_IDLE;
unsigned long bellPhaseStartMs = 0, bellStartMs = 0;
uint8_t bellTrack = 0;
bool bellTest = false, bellAudioStarted = false;
bool dbgBusyPrev = false, dbgBusyFirst = true;
unsigned long dbgPlayCmdMs = 0, dbgLastStatusLog = 0;
const char* dbgStopReason = "NONE";
SchedEntry scheduleCache[SCHEDULE_MAX];
int scheduleCount = 0;
unsigned long lastSchedCheckMs = 0, lastScheduleSyncMs = 0;
bool scheduleSyncRequested = false, syncWasImmediate = false, initialScheduleSyncPending = false;
String pendingCommandResponse;
volatile bool pendingCommandResponseReady = false;
